import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/nav-bar";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      <link rel="icon" href="/favicon" sizes="any" />
      </head>
      <body className={inter.className}>
        <main>
          <NavBar />
          <div className="my-24 p-3 pb-0 lg:px-28">
          {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
